
// Endpoint Criar turma
POST http://localhost:3003/class
Content-Type: application/json

{
"name": "Turma do Patrick",
"module": 4

}

###

// Endpoint buscar turmas

GET http://localhost:3003/allclasses


###

PUT http://localhost:3003/classChange
Content-Type: application/json

{
    "id":"1662727807540",
    "module":8
}