
// Endpoint Criar turma
POST http://localhost:3003/class
Content-Type: application/json

{
"name": "Turma do Patrick",
"module": 5

}

###

// Endpoint buscar turmas

GET http://localhost:3003/allclasses


###

//Endpoint alterar Modulos.

PUT http://localhost:3003/classChange
Content-Type: application/json

{
    "id":"1662727807540",
    "module":9
}

###

// Endpoint criação de estudante

POST http://localhost:3003/student
Content-Type: application/json

{
        "name": "fer",
        "email": "fer@fer.com",
        "data_nasc":"06/06/1986",
        "turma_id": "1662724843822",

}

### 

// Endpoint procurar Aluno por nome 
GET http://localhost:3003/student/:Fernanda
